apiVersion: v1
kind: Service
metadata:
  name: session-app
  labels:
    app: session-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: session-app